SET NAMES utf8mb4;
USE `gttournament`;
INSERT INTO schools(id,name) VALUES (1,'Odborné učiliště, Cvrčovice 131, Pohořelice');
INSERT INTO schools(id,name) VALUES (2,'Gymnázium Jana Blahoslava, Lány 2, Ivančice');
INSERT INTO schools(id,name) VALUES (3,'Střední odborná škola FORTIKA, Tišnovská 15, Lomnice u Tišnova');
INSERT INTO schools(id,name) VALUES (4,'SOŠ zahradnická a SOU, Masarykova 198, Rajhrad');
INSERT INTO schools(id,name) VALUES (5,'Integrovaná střední škola, , Sokolnice 496');
INSERT INTO schools(id,name) VALUES (6,'Gymnázium a ZUŠ, Riegrova 17, Šlapanice');
INSERT INTO schools(id,name) VALUES (7,'Gymnázium, Tyršova 400, Židlochovice');
INSERT INTO schools(id,name) VALUES (8,'Střední škola a Základní škola Tišnov, nám. Míru 22, Tišnov');
INSERT INTO schools(id,name) VALUES (9,'Gymnázium T. G. Masaryka, U Školy 39, Zastávka');
INSERT INTO schools(id,name) VALUES (10,'ISŠ - COP, Olomoucká 61, Brno');
INSERT INTO schools(id,name) VALUES (11,'Střední škola inf. tech. a soc. péče, Purkyňova 97, Brno');
INSERT INTO schools(id,name) VALUES (12,'Střední škola F. D. Roosevelta pro TP, Křižíkova 11/1694, Brno');
INSERT INTO schools(id,name) VALUES (13,'SOŠ a SOU stavební, Pražská 38b, Brno - Bosonohy');
INSERT INTO schools(id,name) VALUES (14,'ISŠ automobilní, Křižíkova 15, Brno');
INSERT INTO schools(id,name) VALUES (15,'SPŠ a VOŠ technická, Sokolská 1, Brno');
INSERT INTO schools(id,name) VALUES (16,'SOŠ a SOU strojírenské a elektrotech., Trnkova 113, Brno - Líšeň');
INSERT INTO schools(id,name) VALUES (17,'BEZPEČNOSTNĚ PRÁVNÍ AKADEMIE BRNO, S.R.O.');
INSERT INTO schools(id,name) VALUES (18,'Gymnázium, Terezy Novákové 2, Brno - Řečkovice');
INSERT INTO schools(id,name) VALUES (19,'Gymnázium J. G. Mendela a jeho zař. a ZUŠ, Mendlovo nám. č. p. 1, č. o. 3/4, Brno');
INSERT INTO schools(id,name) VALUES (20,'I. Německé zemské gymnasium, ZŠ a MŠ, o.p.s., Mendlovo nám. 1/ 3,4, Brno');
INSERT INTO schools(id,name) VALUES (21,'Gymnázium Tišnov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (22,'Střední odborná škola a Střední odborné učiliště Kuřim');
INSERT INTO schools(id,name) VALUES (23,'Gymnázium, Praha 5, Na Zatlance 11');
INSERT INTO schools(id,name) VALUES (24,'Obchodní akademie a vyšší odborná škola Brno, Kotlářská, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (25,'Odborné učiliště a praktická škola Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (26,'Střední průmyslová škola stavební Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (27,'Střední škola Brno, Charbulova, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (28,'Střední škola polytechnická Brno, Jílová, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (29,'AKADEMIA Gymnázium, Základní škola a Mateřská škola, s. r. o.');
INSERT INTO schools(id,name) VALUES (30,'Církevní střední zdravotnická škola s. r. o.');
INSERT INTO schools(id,name) VALUES (31,'Gymnázium Globe, s. r. o.');
INSERT INTO schools(id,name) VALUES (32,'Hotelová škola s. r. o.');
INSERT INTO schools(id,name) VALUES (33,'Mateřská škola, základní škola a střední škola Gellnerka Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (34,'Obchodní akademie ELDO, o. p. s.');
INSERT INTO schools(id,name) VALUES (35,'Střední odborná škola EDUCAnet Brno, o. p. s.');
INSERT INTO schools(id,name) VALUES (36,'Střední odborné učiliště tradičních řemesel a Vyšší odborná škola, spol. s r. o.');
INSERT INTO schools(id,name) VALUES (37,'Střední průmyslová škola chemická Brno, Vranovská, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (38,'Střední škola Gemini Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (39,'Střední škola grafická Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (40,'Střední škola informatiky, poštovnictví a finančnictví Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (41,'Střední škola KNIH, o. p. s.');
INSERT INTO schools(id,name) VALUES (42,'Střední zdravotnická škola Brno, Jaselská, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (43,'TRIVIS – Střední škola veřejnoprávní Brno, s. r. o.');
INSERT INTO schools(id,name) VALUES (44,'TRIVIS – Střední škola veterinární Emila Holuba Brno, s. r. o.');
INSERT INTO schools(id,name) VALUES (45,'Gymnázium Brno, Slovanské náměstí, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (46,'Střední škola technická a dopravní Gustava Habrmana Česká Třebová');
INSERT INTO schools(id,name) VALUES (47,'SOŠ a SOU Hustopeče');
INSERT INTO schools(id,name) VALUES (48,'Základní škola Tišnov, nám. 28. října 1708, Tišnov');
INSERT INTO schools(id,name) VALUES (49,'Biskupské gymnázium Brno a mateřská škola');
INSERT INTO schools(id,name) VALUES (50,'Cyrilometodějské gymnázium a střední odborná škola pedagogická Brno');
INSERT INTO schools(id,name) VALUES (51,'EKO GYMNÁZIUM BRNO o. p. s.');
INSERT INTO schools(id,name) VALUES (52,'Gymnázium Brno, Elgartova, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (53,'Gymnázium Brno, Křenová, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (54,'Gymnázium Brno, třída Kapitána Jaroše, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (55,'Gymnázium Brno, Vídeňská, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (56,'Gymnázium Brno-Bystrc, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (57,'Gymnázium Matyáše Lercha, Brno, Žižkova 55, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (58,'Gymnázium Mojmírovo náměstí s. r. o.');
INSERT INTO schools(id,name) VALUES (59,'Gymnázium P. Křížkovského s uměleckou profilací, s. r. o.');
INSERT INTO schools(id,name) VALUES (60,'Konzervatoř Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (61,'Moravské gymnázium Brno s. r. o.');
INSERT INTO schools(id,name) VALUES (62,'ScioŠkola Brno – střední škola, s. r. o.');
INSERT INTO schools(id,name) VALUES (63,'Sportovní gymnázium Ludvíka Daňka, Brno, Botanická 70, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (64,'Střední odborná škola managementu a práva, s. r. o.');
INSERT INTO schools(id,name) VALUES (65,'Střední odborná škola MORAVA o. p. s.');
INSERT INTO schools(id,name) VALUES (66,'Střední škola uměleckomanažerská, s. r. o.');
INSERT INTO schools(id,name) VALUES (67,'Střední škola umění a designu a Vyšší odborná škola Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (68,'Střední zdravotnická škola a Vyšší odborná škola zdravotnická Brno, Merhautova, příspěvková organiza');
INSERT INTO schools(id,name) VALUES (69,'Střední zdravotnická škola Evangelické akademie');
INSERT INTO schools(id,name) VALUES (70,'Taneční konzervatoř Brno, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (71,'Základní škola a gymnázium Ježek bez klece');
INSERT INTO schools(id,name) VALUES (72,'Základní škola a praktická škola Brno, Vídeňská, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (73,'Gymnázium Blansko, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (74,'Střední škola technická a gastronomická Blansko, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (75,'Střední škola cestovního ruchu a gastronomie, s. r. o.');
INSERT INTO schools(id,name) VALUES (76,'Obchodní akademie a Střední zdravotnická škola Blansko, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (77,'Střední škola André Citroëna Boskovice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (78,'Střední pedagogická škola Boskovice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (79,'Gymnázium Boskovice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (80,'Mateřská škola, základní škola a praktická škola Boskovice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (81,'Vyšší odborná škola a střední škola Boskovice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (82,'Střední průmyslová škola Jedovnice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (83,'Masarykova střední škola Letovice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (84,'Výchovný ústav a střední škola, Olešnice na Moravě, Trpínská 317');
INSERT INTO schools(id,name) VALUES (85,'Gymnázium Rájec-Jestřebí, o. p. s.');
INSERT INTO schools(id,name) VALUES (86,'Střední průmyslová škola Edvarda Beneše a obchodní akademie Břeclav, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (87,'Soukromá střední odborná škola manažerská a zdravotnická s. r. o.');
INSERT INTO schools(id,name) VALUES (88,'Gymnázium a Jazyková škola s právem státní jazykové zkoušky Břeclav, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (89,'Střední odborná škola a střední odborné učiliště Hustopeče, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (90,'Gymnázium T. G. Masaryka Hustopeče, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (91,'Základní škola a praktická škola Hustopeče, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (92,'Městská střední odborná škola, Klobouky u Brna, nám. Míru 6, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (93,'Gymnázium a střední odborná škola Mikulov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (94,'Soukromá střední průmyslová škola Břeclav, spol. s r. o. CULTUS');
INSERT INTO schools(id,name) VALUES (95,'Střední vinařská škola Valtice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (96,'Gymnázium, Velké Pavlovice, Pod Školou 10, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (97,'Střední škola gastronomie, hotelnictví a lesnictví Bzenec, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (98,'Integrovaná střední škola Hodonín, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (99,'Střední škola průmyslová a umělecká Hodonín, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (100,'Gymnázium, Obchodní akademie a Jazyková škola s právem státní jazykové zkoušky Hodonín, příspěvková');
INSERT INTO schools(id,name) VALUES (101,'Základní škola a praktická škola Hodonín, náměstí B. Martinů, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (102,'Střední škola automobilní Kyjov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (103,'Klvaňovo gymnázium a střední zdravotnická škola Kyjov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (104,'Střední odborné učiliště Kyjov, příspěvková organizace (od 1. 1. 2022 Střední škola polytechnická Ky');
INSERT INTO schools(id,name) VALUES (105,'Střední škola Strážnice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (106,'Veřejnosprávní akademie a střední škola, s. r. o.');
INSERT INTO schools(id,name) VALUES (107,'Purkyňovo gymnázium, Strážnice, Masarykova 379, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (108,'Obchodní akademie a Střední odborné učiliště Veselí nad Moravou, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (109,'Základní škola a praktická škola Veselí nad Moravou, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (110,'Gymnázium a obchodní akademie Bučovice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (111,'Integrovaná střední škola Slavkov u Brna, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (112,'Základní škola a praktická škola, Slavkov u Brna, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (113,'Střední odborná škola a Střední odborné učiliště Vyškov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (114,'Gymnázium a Střední odborná škola zdravotnická a ekonomická Vyškov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (115,'Mateřská škola, základní škola a střední škola Vyškov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (116,'Gymnázium Moravský Krumlov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (117,'Střední škola dopravy, obchodu a služeb Moravský Krumlov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (118,'Výchovný ústav, dětský domov se školou, středisko výchovné péče, střední škola a základní škola, Mor');
INSERT INTO schools(id,name) VALUES (119,'Výchovný ústav, střední škola a školní jídelna Višňové, Zámek 1');
INSERT INTO schools(id,name) VALUES (120,'Střední odborné učiliště a Střední odborná škola SČMSD, Znojmo, s. r. o.');
INSERT INTO schools(id,name) VALUES (121,'Střední škola technická Znojmo, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (122,'Gymnázium Dr. Karla Polesného Znojmo, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (123,'Gymnázium, Střední pedagogická škola, Obchodní akademie a Jazyková škola s právem státní jazykové zk');
INSERT INTO schools(id,name) VALUES (124,'Mateřská škola, základní škola a praktická škola Znojmo, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (125,'Střední odborná škola Znojmo, Dvořákova, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (126,'Střední zdravotnická škola a Vyšší odborná škola zdravotnická Znojmo, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (127,'Gymnázium Aš, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (128,'Základní škola a střední škola Aš, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (129,'Integrovaná střední škola Cheb, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (130,'Gymnázium Cheb, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (131,'Střední zdravotnická škola a vyšší odborná škola Cheb, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (132,'Svobodná chebská škola, základní škola a gymnázium s. r. o.');
INSERT INTO schools(id,name) VALUES (133,'Gymnázium a obchodní akademie Mariánské Lázně, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (134,'Hotelová škola Mariánské Lázně, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (135,'JEZDECKÁ AKADEMIE – střední odborná škola Mariánské Lázně s. r. o.');
INSERT INTO schools(id,name) VALUES (136,'Střední škola logistická Dalovice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (137,'Střední odborná škola stavební Karlovy Vary, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (138,'Střední pedagogická škola, gymnázium a vyšší odborná škola Karlovy Vary, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (139,'Střední škola stravování a služeb Karlovy Vary, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (140,'Soukromá obchodní akademie Podnikatel, spol. s r. o.');
INSERT INTO schools(id,name) VALUES (141,'Obchodní akademie, vyšší odborná škola cestovního ruchu a jazyková škola s právem státní jazykové zk');
INSERT INTO schools(id,name) VALUES (142,'Střední uměleckoprůmyslová škola keramická a sklářská Karlovy Vary, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (143,'Základní škola a střední škola Karlovy Vary, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (144,'První české gymnázium v Karlových Varech, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (145,'TRIVIS – Střední škola veřejnoprávní Karlovy Vary, s. r. o.');
INSERT INTO schools(id,name) VALUES (146,'Střední odborná škola Karlovy Vary, s. r. o.');
INSERT INTO schools(id,name) VALUES (147,'Střední zdravotnická škola a vyšší odborná škola zdravotnická Karlovy Vary, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (148,'Střední průmyslová škola Ostrov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (149,'Gymnázium Ostrov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (150,'Střední lesnická škola Žlutice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (151,'Střední škola, základní škola a mateřská škola Kraslice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (152,'Vojenská střední škola a Vyšší odborná škola Ministerstva obrany v Moravské Třebové (pracoviště Soko');
INSERT INTO schools(id,name) VALUES (153,'Integrovaná střední škola technická a ekonomická Sokolov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (154,'Střední škola živnostenská Sokolov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (155,'Gymnázium Sokolov a Krajské vzdělávací centrum, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (156,'Soukromá obchodní akademie Sokolov, s. r. o.');
INSERT INTO schools(id,name) VALUES (157,'Škola Můj Projekt Mánesova – gymnázium, základní škola a mateřská škola s. r. o.');
INSERT INTO schools(id,name) VALUES (158,'Vyšší policejní škola a Střední policejní škola Ministerstva vnitra v Praze (pracoviště Sokolov)');
INSERT INTO schools(id,name) VALUES (159,'Střední škola vizuální tvorby, s. r. o.');
INSERT INTO schools(id,name) VALUES (160,'Střední škola a vyšší odborná škola aplikované kybernetiky s. r. o.');
INSERT INTO schools(id,name) VALUES (161,'Střední škola Sion High School, Hradec Králové');
INSERT INTO schools(id,name) VALUES (162,'Hotelová škola Hradec Králové, s. r. o.');
INSERT INTO schools(id,name) VALUES (163,'Střední uměleckoprůmyslová škola hudebních nástrojů a nábytku, Hradec Králové, 17. listopadu 1202');
INSERT INTO schools(id,name) VALUES (164,'Biskupské gymnázium, církevní základní škola, mateřská škola a základní umělecká škola Hradec Králov');
INSERT INTO schools(id,name) VALUES (165,'Gymnázium Boženy Němcové, Hradec Králové, Pospíšilova tř. 324');
INSERT INTO schools(id,name) VALUES (166,'Gymnázium J. K. Tyla, Hradec Králové, Tylovo nábř. 682');
INSERT INTO schools(id,name) VALUES (167,'Mateřská škola, základní škola a střední škola Daneta, s. r. o.');
INSERT INTO schools(id,name) VALUES (168,'Obchodní akademie, Střední odborná škola a Jazyková škola s právem státní jazykové zkoušky, Hradec K');
INSERT INTO schools(id,name) VALUES (169,'Obchodní akademie, Střední pedagogická škola, Vyšší odborná škola cestovního ruchu a Jazyková škola');
INSERT INTO schools(id,name) VALUES (170,'PROINTEPO – Střední škola, Základní škola a Mateřská škola s. r. o.');
INSERT INTO schools(id,name) VALUES (171,'První soukromé jazykové gymnázium Hradec Králové spol. s r. o.');
INSERT INTO schools(id,name) VALUES (172,'Střední odborná škola a Střední odborné učiliště, Hradec Králové, Vocelova 1338');
INSERT INTO schools(id,name) VALUES (173,'Střední odborná škola veterinární, Hradec Králové-Kukleny, Pražská 68');
INSERT INTO schools(id,name) VALUES (174,'Střední průmyslová škola stavební, Hradec Králové, Pospíšilova tř. 787');
INSERT INTO schools(id,name) VALUES (175,'Střední průmyslová škola, Střední odborná škola a Střední odborné učiliště, Hradec Králové');
INSERT INTO schools(id,name) VALUES (176,'Střední škola profesní přípravy, Hradec Králové');
INSERT INTO schools(id,name) VALUES (177,'Střední škola služeb, obchodu a gastronomie');
INSERT INTO schools(id,name) VALUES (178,'Vyšší odborná škola zdravotnická a Střední zdravotnická škola, Hradec Králové, Komenského 234');
INSERT INTO schools(id,name) VALUES (179,'Vyšší odborná škola, Střední škola, Základní škola a Mateřská škola, Hradec Králové, Štefánikova 549');
INSERT INTO schools(id,name) VALUES (180,'Gymnázium, Střední odborná škola a Vyšší odborná škola, Nový Bydžov');
INSERT INTO schools(id,name) VALUES (181,'Střední škola technická a řemeslná, Nový Bydžov, Dr. M. Tyrše 112');
INSERT INTO schools(id,name) VALUES (182,'TRIVIS – Střední škola veřejnoprávní Třebechovice pod Orebem, s. r. o.');
INSERT INTO schools(id,name) VALUES (183,'Zemědělská akademie a Gymnázium Hořice – střední škola a vyšší odborná škola, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (184,'Střední uměleckoprůmyslová škola sochařská a kamenická, Hořice, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (185,'Hořické gymnázium');
INSERT INTO schools(id,name) VALUES (186,'Střední škola řemesel a Základní škola, Hořice');
INSERT INTO schools(id,name) VALUES (187,'Lepařovo gymnázium, Jičín, Jiráskova 30');
INSERT INTO schools(id,name) VALUES (188,'Masarykova obchodní akademie, Jičín, 17. listopadu 220');
INSERT INTO schools(id,name) VALUES (189,'Soukromá střední škola podnikatelská – ALTMAN, s. r. o.');
INSERT INTO schools(id,name) VALUES (190,'Vyšší odborná škola a Střední průmyslová škola, Jičín, Pod Koželuhy 100');
INSERT INTO schools(id,name) VALUES (191,'Základní škola a Praktická škola, Jičín');
INSERT INTO schools(id,name) VALUES (192,'Střední škola zahradnická, Kopidlno, náměstí Hilmarovo 1');
INSERT INTO schools(id,name) VALUES (193,'Gymnázium a Střední odborná škola pedagogická, Nová Paka, Kumburská 740');
INSERT INTO schools(id,name) VALUES (194,'Gymnázium a Střední odborná škola pedagogická, Nová Paka, Kumburská 740');
INSERT INTO schools(id,name) VALUES (195,'Střední škola strojírenská a elektrotechnická');
INSERT INTO schools(id,name) VALUES (196,'Gymnázium, Broumov, Hradební 218');
INSERT INTO schools(id,name) VALUES (197,'Základní škola a Praktická škola, Broumov');
INSERT INTO schools(id,name) VALUES (198,'Střední průmyslová škola Otty Wichterleho, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (199,'Střední odborná škola sociální a zdravotnická – Evangelická akademie');
INSERT INTO schools(id,name) VALUES (200,'Střední škola řemeslná, Jaroměř, Studničkova 260');
INSERT INTO schools(id,name) VALUES (201,'Střední průmyslová škola stavební a Obchodní akademie arch. Jana Letzela, Náchod, příspěvková organi');
INSERT INTO schools(id,name) VALUES (202,'ACADEMIA MERCURII soukromá střední škola, s. r. o.');
INSERT INTO schools(id,name) VALUES (203,'Gymnázium Jaroslava Žáka, Jaroměř');
INSERT INTO schools(id,name) VALUES (204,'Jiráskovo gymnázium, Náchod, Řezníčkova 451');
INSERT INTO schools(id,name) VALUES (205,'Praktická škola, Základní škola a Mateřská škola Josefa Zemana, Náchod');
INSERT INTO schools(id,name) VALUES (206,'Střední průmyslová škola, Odborná škola a Základní škola, Nové Město nad Metují');
INSERT INTO schools(id,name) VALUES (207,'Gymnázium, Dobruška, Pulická 779');
INSERT INTO schools(id,name) VALUES (208,'Střední průmyslová škola elektrotechniky a informačních technologií, Dobruška, Čs. odboje 670');
INSERT INTO schools(id,name) VALUES (209,'Střední škola – Podorlické vzdělávací centrum, Dobruška');
INSERT INTO schools(id,name) VALUES (210,'Základní škola,Kuřim, Jungmannova 813, okres Brno – venkov, příspěvková organizace');
INSERT INTO schools(id,name) VALUES (211,'SPŠ, SOŠ a SOU, Hradec Králové, Hradební');
INSERT INTO schools(id,name) VALUES (212,'Střední škola, Rokycany, Jeřabinová 96/III');
INSERT INTO schools(id,name) VALUES (213,'Gymnázium Vojtecha Mihálika Sereď');
INSERT INTO schools(id,name) VALUES (214,'Základní a mateřská škola Dolní kounice');
INSERT INTO schools(id,name) VALUES (215,'Základní škola a Mateřská škola Dolní Loučky');
